# Deploy all root folders in the repository to GitHub Pages
name: Deploy all folders to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy all root folders
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare combined deployment directory
        run: |
          mkdir -p _site
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d ! -name "_site" ! -name ".git" ! -name ".github"); do
            echo "Including directory: $dir"
            cp -r "$dir" "_site/"
          done
          echo "Final structure:"
          find _site -maxdepth 2 -type f

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
